- name: docker-compose up
  docker_compose:
    project_name: watchtower
    pull: yes
    definition: 
      version: "3"
      services:
        app:
          container_name: watchtower
          image: containrrr/watchtower
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "/home/{{ default_ansible_user }}/.docker/config.json:/config.json"
          restart: unless-stopped
