sonar.projectKey=hackerembassy_hackerembassy-tg-bot
sonar.organization=hackerembassy
sonar.projectName=hackerembassy-tg-bot
sonar.projectVersion=1.0

sonar.exclusions=tests/**/*

sonar.issue.ignore.multicriteria=e1,e2

sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S2094
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S3735
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info


