- name: supplementary packages installed
  become: yes
  apt:
    update_cache: yes
    name:
      - gnupg

- name: gpg key downloaded to localhost
  become: no
  get_url:
    url: "{{ apt_repo_gpg_key_url }}"
    checksum: "{{ apt_repo_gpg_key_checksum }}"
    dest: "/tmp/{{ apt_repo_gpg_key_name }}"
  register: gpg_key
  delegate_to: localhost
  retries: 5
  delay: 2
  until: gpg_key is succeeded
  run_once: true
  check_mode: false

- name: gpg key added to host keyrings
  become: yes
  command:
    cmd: gpg --dearmor -o {{ apt_repo_gpg_key_target_path }}
    stdin: "{{ lookup('file', gpg_key.dest) }}"
    creates: "{{ apt_repo_gpg_key_target_path }}"
  when: not ansible_check_mode

- name: apt repository added
  become: yes
  apt_repository:
    repo: "{{ apt_repo_source }}"
    update_cache: yes

- name: apt packages installed
  become: yes
  apt:
    name: "{{ apt_packages }}"
  when: apt_packages is defined
