- name: container updated
  import_role:
    name: dockerized_service
  vars:
    service_name: he-bot
    docker_volumes:
      - he-bot-data
      - "{{ config_volume }}"
    config_volume: he-bot-config
    config_volume_templates:
      - src: production.json.j2
        dest: production.json
    docker_compose_definition:
      version: '3.8'
      services:
        app:
          container_name: "{{ service_name }}"
          image: ghcr.io/hackerembassy/hackerembassy-tg-bot:ci-cd  # TODO
          volumes:
            - config:/app/config
            - data:/app/data
          environment:
            - NODE_ENV=production
            - HACKERBOTTOKEN={{ hacker_bot_token }}
          restart: unless-stopped
      volumes:
        config:
          name: he-bot-config
          external: true
        data:
          name: he-bot-data
          external: true
