FROM docker.io/library/node:lts-alpine
RUN apk add g++ make python
WORKDIR /app
COPY . .
RUN mv ./deploy/entrypoint.sh / &&\
    chmod +x /entrypoint.sh &&\
    npm ci
ENTRYPOINT ["/entrypoint.sh"]
CMD ["npm", "run", "start"]
