FROM docker.io/library/node:lts-alpine
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
WORKDIR /app
COPY . .
RUN mv ./deploy/entrypoint.sh / &&\
    chmod +x /entrypoint.sh &&\
    npm ci
ENTRYPOINT ["/entrypoint.sh"]
CMD ["npm", "run", "start"]
