- name: container updated
  import_role:
    name: dockerized_service
  vars:
    service_name: hackem-bot
    docker_volumes:
      - "{{ service_name }}-db"
      - "{{ config_volume }}"
    config_volume: "{{ service_name }}-config"
    config_volume_templates:
      - src: production.json.j2
        dest: production.json
    config_volume_files:
      - src: pub.key
        dest: pub.key
      - src: priv.key.vault
        dest: priv.key
    docker_compose_definition:
      version: '3.8'
      services:
        app:
          container_name: "{{ service_name }}"
          image: ghcr.io/hackerembassy/hackerembassy-tg-bot:ci-cd  # TODO
          volumes:
            - config:/app/config/sec
            - db:/app/data/db
          environment:
            - NODE_ENV=production
            - BOTDEBUG=false
            - HACKERBOTTOKEN={{ hackem_bot_token }}
            - UNLOCKKEY={{ hackem_key }}
          restart: unless-stopped
      volumes:
        config:
          name: "{{ config_volume }}"
          external: true
        db:
          name: "{{ service_name }}-db"
          external: true
