name: Deploy containers via docker-compose
inputs:
  ssh_user:
    description: deploy target user
    required: true
  ssh_identity:
    description: string for known_hosts file
    required: true
  ssh_key:
    description: string for id_ed25519 file
    required: true
  ssh_host:
    description: deploy target host
    required: true
  ssh_port:
    description: deploy target port
    required: true
  docker_volume:
    description: docker volume to backup
    required: true

runs:
  using: composite
  steps:
    -
      name: Put server's SSH key
      uses: ./.github/actions/ssh-keys
      with:
        action: put
        identity: ${{ inputs.ssh_identity }}
        key: ${{ inputs.ssh_key }}
    -
      name: Deploy
      shell: bash
      run: |
        echo '
          Host prod
            HostName ${{ inputs.ssh_host }}
            Port ${{ inputs.ssh_port }}
            User ${{ inputs.ssh_user }}
        ' >> ~/.ssh/config
        ssh -T prod '
          set -xe
          docker_volume=${{ inputs.docker_volume }}
          proxy=$(docker run --detach --rm -v $docker_volume:/v  busybox  sleep 900)
          tmp=$(mktemp --directory)
          docker cp  $proxy:/v  $tmp/$docker_volume
          docker rm --force $proxy
          rm -f "~/$docker_volume.tar"
          tar -cf ~/$docker_volume.tar  -C $tmp  $docker_volume
          rm -r "$tmp"
        '
        scp prod:'~/${{ inputs.docker_volume }}.tar' ./${{ inputs.docker_volume }}.tar
    -
      name: Destroy server's SSH key
      uses: ./.github/actions/ssh-keys
      with:
        action: destroy
