name: Manage SSH keys
inputs:
  alias:
    description: name of the ssh connection
    required: false
    default: prod
  host:
    description: hostname or IP address
    required: false
  port:
    description: ssh port
    required: false
    default: 22
  user:
    description: ssh user
    required: false
    default: root
  identity:
    description: string for known_hosts file
    required: false
  key:
    description: string for id_ed25519 file
    required: false
  action:
    description: put or destroy
    required: false
    default: put

runs:
  using: composite
  steps:
    -
      if: ${{ inputs.action == 'put' }}
      shell: bash
      run: |
        mkdir -v ~/.ssh
        echo "${{ inputs.identity }}" > ~/.ssh/known_hosts
        echo "${{ inputs.key }}" > ~/.ssh/id_ed25519
        chmod -v 600 ~/.ssh/*
    -
      if: ${{ inputs.action == 'put' && inputs.host }}
      shell: bash
      run: |
        echo '
          Host ${{ inputs.alias }}
            HostName ${{ inputs.host }}
            Port ${{ inputs.port }}
            User ${{ inputs.user }}
        ' >> ~/.ssh/config
    -
      if: ${{ inputs.action == 'destroy' }}
      shell: bash
      run: shred -v ~/.ssh/*
