name: Manage SSH keys
inputs:
  identity:
    description: string for known_hosts file
    required: false
  key:
    description: string for id_ed25519 file
    required: false
  action:
    required: true
    description: put or destroy
    default: put
runs:
  using: composite
  steps:
    -
      if: ${{ inputs.action == 'put' }}
      shell: bash
      run: |
        mkdir -v ~/.ssh
        chmod -v 700 ~/.ssh
        echo "${{ inputs.identity }}" > ~/.ssh/known_hosts
        echo "${{ inputs.key }}" > ~/.ssh/id_ed25519
        chmod -v 600 ~/.ssh/*
    -
      if: ${{ inputs.action == 'destroy' }}
      shell: bash
      run: shred -v ~/.ssh/*
