name: Bot Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      -
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Containerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      -
        uses: ./.github/actions/deploy
        with:
          ssh_user: ci
          ssh_identity: ${{ vars.deploy_target_identity }}
          ssh_host: ${{ secrets.deploy_target_host }}
          ssh_port: ${{ secrets.deploy_target_port }}
          ssh_key: ${{ secrets.deploy_target_key }}
