name: Bot Deployment

on:
  push:
    branches:
      - main
      - ci-cd  # DEBUG

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      -
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        uses: ./.github/actions/deploy
        with:
          ssh_user: ci
          ssh_identity: '|1|RY2fnr8tltHJk97RXktcFWLP6CU=|Q+sQMkU4H3SYupP+XBlB8EVQFSY= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFYdFvcbtPcmrRRJstpQuxE7TdPR2+yCbAcOfn5Aa1uq'
          ssh_host: ${{ secrets.deploy_target_host }}
          ssh_port: ${{ secrets.deploy_target_port }}
          ssh_key: ${{ secrets.deploy_target_key }}
